version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chitechtask
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - testnetwork

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: flask-app
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "5000:5000"
    networks:
      - testnetwork


networks:
  testnetwork:
    driver: bridge

volumes:
  pg_data: